replicaCount: 3

image:
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: genesis.local

config:
  dbHost: "postgres-service"
  appEnv: "production"
  logLevel: "info"
