apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-creds
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.db.username | quote }}
  password: {{ .Values.db.password | quote }}
