name: Genesis CI/CD

on:
  push:
    branches: [main, hw30]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        shell: bash
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        shell: bash
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/genesis:${{ github.sha }} .

      - name: Push Docker image
        shell: bash
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/genesis:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/genesis:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/genesis:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/genesis:latest
